### ISSUE TITLE
Pipeline Presentation Preparation

### ISSUE THREAD

**Issue by JoanaVillanova** [lsus-csc-jc/ECIMS#8]
**- Tasks:**
  - [x] Slide Creation: Develop slides covering key aspects of the project.
  - [x] Research: Gather information and data to support the presentation. 
  - [x] Slide Creation: Develop slides covering key aspects of the project.

**Comment by JoanaVillanova** [comment]
**- Tasks:**
  - [ ] Slide Creation: Develop slides covering key aspects of the project.
  - [ ] Research: Gather information and data to support the presentation. 
  - [ ] Slide Creation: Develop slides covering key aspects of the project.
